### ISSUE TITLE
Add API to suppress logging on multiple `initialization` calls

### ISSUE THREAD

**Issue by NotWoods** [mozilla/glean#1127]
In Fenix, Glean is initialized inside the `Application` class. Every Roboletric test runs `Application.onCreate`, meaning Glean is re-initialized many times inside of tests. This adds some unrelated logs to many unit tests that don't touch Glean, so a way to turn off the logging would be appreciated.

**Comment by Dexterp37** [comment]
Thank you for filing this. We're using Bugzilla as our main tracking tool, so I filed it [there](https://bugzilla.mozilla.org/show_bug.cgi?id=1657290). Closing this!
