### ISSUE TITLE
Execution failed for task ':app:gleanGenerateMetricsDocsForDebug'. > Glean documentation generation failed.

### ISSUE THREAD

**Issue by RasoolMohamed27** [mozilla/glean#1409]
Please help to resolve the below build error in the Android project.

> Task :app:gleanGenerateMetricsDocsForDebug

Glean SDK - generating docs for E:\Examples\fenix-master\fenix-master\app\metrics.yaml in E:\Examples\fenix-master\fenix-master/docs

Glean SDK - generating docs for E:\Examples\fenix-master\fenix-master\app\pings.yaml in E:\Examples\fenix-master\fenix-master/docs

**> Task :app:gleanGenerateMetricsDocsForDebug FAILED

Execution failed for task ':app:gleanGenerateMetricsDocsForDebug'.
> Glean documentation generation failed.**

**Comment by Dexterp37** [comment]
@RasoolMohamed27 thanks for reaching out.

Are you building from within Android Studio or from the command line? Can you provide more information about your environment?

**Comment by RasoolMohamed27** [comment]
@Dexterp37 

I'm building from the Android Studio

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37
> 
> I'm building from the Android Studio

@RasoolMohamed27 sometimes the IDE hides the culprit of the error. Can you try to build Fenix from the command line and see what the real error is?

**Comment by RasoolMohamed27** [comment]
@Dexterp37 Please find the screenshot from the command line.

![image](https://user-images.githubusercontent.com/29065598/103540722-31bba300-4ec0-11eb-91c7-57ecfeeaaa0d.png)

![image](https://user-images.githubusercontent.com/29065598/103540853-69c2e600-4ec0-11eb-8f80-ec8f3070c04e.png)

![image](https://user-images.githubusercontent.com/29065598/103540914-85c68780-4ec0-11eb-91fb-5252c9711502.png)

**Comment by Dexterp37** [comment]
> ![image](https://user-images.githubusercontent.com/29065598/103540914-85c68780-4ec0-11eb-91fb-5252c9711502.png)

This image seems to show the culprit: `ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.`. Looks like there's a problem with the PATH for Python?

**Comment by RasoolMohamed27** [comment]
@Dexterp37 Thank you!

I have fixed it with the help of below link.
https://stackoverflow.com/a/55642416/7758211

**Comment by Dexterp37** [comment]
Glad it worked! I'm closing this issue. Please open a new one in case of other problems! :-)
