### ISSUE TITLE
glean might report incomplete/misleading `locale` in `client_info`

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla/glean#1573]
In certain Huawei devices shipped in mainland China, when an user choose `Traditional Chinese` in its OS settings, the system locale as returned from `Locale.getDefault()` is `zh-Hant-CN`.

With such a system setting `zh-TW` strings would be displayed if available, while glean would still report it as `zh-CN`.

I think this is the result of [unconditional omission of the `script` subtag in the `getLocaleTag` function](https://github.com/mozilla/glean/blob/v36.0.0/glean-core/android/src/main/java/mozilla/telemetry/glean/utils/LocaleUtils.kt#L9-L35).

**Comment by Dexterp37** [comment]
Hi @l-hedgehog , thanks for filing this. I filed this bug on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1703193).
