### ISSUE TITLE
Bump `rust-android-gradle` to version 0.9.0+

### ISSUE THREAD

**Issue by ncalexan** [mozilla/glean#1762]
Hello Glean Team!  I just want to let y'all know that I put some energy into https://github.com/mozilla/rust-android-gradle and as of version 0.9.0 the plugin should support more versions of Gradle and the Android-Gradle plugin.  If you were not updating those components due to `rust-android-gradle`, you should be able to update with newer versions.

**Comment by badboy** [comment]
We use bugzilla for tracking, so I moved it over there: https://bugzilla.mozilla.org/show_bug.cgi?id=1727589
