### ISSUE TITLE
(Very uncommon) NPE in Glean.initialize in FFTV

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla/glean#187]
This is super low priority, as far as I'm aware we've only seen one instance of this crash in the wild.  But since it's an NPE, I thought it might be useful for you to be aware of it.

### Exception details

`NullPointerException`
`Attempt to read from null array`
<img width="1024" alt="Screen Shot 2019-07-18 at 1 27 32 PM" src="https://user-images.githubusercontent.com/13170306/61489554-d7432580-a95f-11e9-9819-3e7deb48107f.png">

[This is the line referenced.](https://github.com/mozilla-mobile/firefox-tv/blob/releases/v3.11/app/src/main/java/org/mozilla/tv/firefox/FirefoxApplication.kt#L87)

If you decide to you'd like you investigate deeper into this, we can get you access to [the crash on Sentry](https://sentry.prod.mozaws.net/operations/firefox-tv/issues/6061969/?query=is:unresolved).  It has some more information about the device that might be helpful.

**Comment by badboy** [comment]
Hey, thanks for the report. I moved this bug over to [bugzilla bug #1567391](https://bugzilla.mozilla.org/show_bug.cgi?id=1567391) to track it.

We'll look into it, NPE should not happen.
