### ISSUE TITLE
Events ping instantiated with wrong name

### ISSUE THREAD

**Issue by ecsmyth** [mozilla/glean#1884]
Expected:
Events ping is instantiated with the name "events." Events ping is sent as [scheduled](https://mozilla.github.io/glean/book/user/pings/events.html). 

Observed:
Events ping is instantiated with the name "[metrics](https://github.com/mozilla/glean/blob/main/glean-core/rlb/src/pings.rs#L47)." Events ping is not sent and Glean logs show the error `ERROR glean_core] Attempted to submit unknown ping 'events'`

STR:
1. In Firefox Desktop, define an event metric and ensure its metrics.yaml is added toolkit/components/glean/metrics_index.py.
1. Instrument Firefox to record the event.
1. Build Firefox using Glean v42.1.0
1. Set the `RUST_LOG` and `GLEAN_DEBUG_VIEW_TAG` environment variables. Rust logging should be at least error level.
1. Mach run the build and perform the action the produces the event
1. Close Firefox
1. Mach run the build again.
1. Observe the rust log in the terminal and lack of events ping in the [Glean Debug ping viewer](https://debug-ping-preview.firebaseapp.com)

**Comment by Dexterp37** [comment]
Thanks for this!
