### ISSUE TITLE
Labelled Counters documentation is confusing with respect to limits

### ISSUE THREAD

**Issue by Standard8** [mozilla/glean#2245]
The [labelled counters documentation](https://mozilla.github.io/glean/book/reference/metrics/labeled_counters.html) has a section under `Recording API` for limits. That section states:

> * Only increments;
> * Saturates at the largest value that can be represented as a 32-bit signed integer.

Further down the page (past the testing API, and into the metrics parameters) under the label section, you get:

> * Conform to the label formatting regular expression.
> * Each label must have a maximum of 60 bytes, when encoded as UTF-8.
> * This list itself is limited to 100 labels.

I feel at least the limit of the number of labels should be included in the limits section at the top of the page - since that is an important limit for this being a labelled counter.

**Comment by Dexterp37** [comment]
Thanks for filing this. We track the SDKs work in Bugzilla, so I filed the [bug there](https://bugzilla.mozilla.org/show_bug.cgi?id=1797934). Let me close this one.
