### ISSUE TITLE
Chain of Trust errors on signing tasks

### ISSUE THREAD

**Issue by ahal** [mozilla/glean#2388]
RyanVM noticed some chain of trust errors:
https://firefox-ci-tc.services.mozilla.com/tasks/groups/CrIshxNpQPGHuAMsnsOjEA

This is due to a key rotation we did last week and the fact that the cached docker-image task was run on a worker that had the old key. To fix it, we'll need to cause a rebuild.

Unfortunately glean is using a non-standard index route which is causing the `add-new-jobs` action to fail, and it is also using an older version of Taskgraph that is missing the `rebuild-cached-tasks` action. Both of these things should be simple to fix.

**Comment by Dexterp37** [comment]
@ahal is there anything needed from us, here?

**Comment by ahal** [comment]
@Dexterp37 Hi, yes.. It looks like there are some gradle failures that are likely caused by my PR:
https://firefox-ci-tc.services.mozilla.com/tasks/EV1q2hJdSa62PBlo46kbyQ/runs/0/logs/live/public/logs/live.log

I think by using the newer decision task image, it caused gradle to upgrade and fail due to incompatibilities. Unfortunately this newer image is needed to upgrade Taskgraph. Do you think these would be easy to resolve (I'm not familiar with gradle)?

@JohanLorenzo have you encountered gradle errors like this while updating any of the mobile repos to the newer Decision image?

**Comment by ahal** [comment]
Also if we just need the signing tasks fixed ASAP, it should be sufficient to land the first commit in that PR.

**Comment by ahal** [comment]
Hm, I think my earlier diagnosis was wrong.

Either that failure is simply an intermittent that is unrelated to my PR, or re-running the `build-docker-image-linux` cached task somehow caused a newer version of gradle to be used (though afaict, that image doesn't install gradle at all).

**Comment by ahal** [comment]
Ok, looks like it was just an unrelated intermittent after all, went green on a re-run.

**Comment by rvandermeulen** [comment]
@travis79 You'll need to respin the 52.3.0 release (or create a new 52.3.1 one) for this issue too.

**Comment by ahal** [comment]
But not quite yet, I'm fixing the scope error that got hit on the push to main.

**Comment by ahal** [comment]
Scopes should be fixed now.

**Comment by ahal** [comment]
Sounds good, we'll need the `build-docker-image-linux` task to run on the `main` branch before the chain of trust error is fixed. But sounds like your crash fix will take care of that. If it doesn't run, please ping me and I'll trigger it manually.
