### ISSUE TITLE
Expose an API to disable glean-managed pings.

### ISSUE THREAD

**Issue by PrototypeNM1** [mozilla/glean#2625]
Glean currently provides the ability to send custom pings with no `client_id`. This allows collecting population wide telemetry without tracking a user across time.

For short lived applications (Firefox background tasks), this conflicts with baseline pings being sent automatically, as the two occur in sufficiently close proximity that it's probable as a vector to deanonymize users.

In order to accommodate this use case, Glean would need to expose a way to prevent baseline pings from being sent.

**Comment by Dexterp37** [comment]
Filed this in bugzilla. Tracking it there.
