### ISSUE TITLE
memory_distribution types cannot set memory_unit

### ISSUE THREAD

**Issue by bdekoz** [mozilla/glean#321]
given this (ostensibly valid via glinter) metrics.yaml file:

network.cache:
  capacity:
    type: memory_distribution
    memory_unit: megabyte
    gecko_datapoint: NETWORK_CACHE_SIZE
    description: |
      Cache size in megabytes keyed by cache capacity calculation type. Numbers are sampled periodically, every time 2GB of data is written to the cache.
    bugs:
      - 1600000
    data_reviews:
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1529352
    notification_emails:
      - telemetry-performance-dev@mozilla.com
    expires: "2020-12-01"

I see the following build error when being assembled via local substitution in fenix nightly:

> Task :app:generateMetricsSourceForGeckoNightlyForPerformanceTest
Glean SDK - generating API from /home/bkoz/.gradle/caches/transforms-2/files-2.1/60ae3cd839ddd6fb60cae15c91c21294/jetified-geckoview-default-71.0.20190925114021/metrics.yaml

> Task :app:compileGeckoNightlyForPerformanceTestKotlin FAILED
e: /home/bkoz/src/mozilla-fenix.git/app/build/generated/source/glean/geckoNightly/forPerformanceTest/kotlin/NetworkCache.kt

[NetworkCache.txt](https://github.com/mozilla/glean/files/3660460/NetworkCache.txt)

: (45, 9): No value passed for parameter 'memoryUnit'

FAILURE: Build failed with an exception.

I'll attach the NetworkCache.kt file (renamed NetworkCache.txt for the filter)
[NetworkCache.txt](https://github.com/mozilla/glean/files/3660461/NetworkCache.txt)

**Comment by Dexterp37** [comment]
You stumbled upon a bug. I put a patch up for fixing this in the parsers.
