### ISSUE TITLE
Add support for sending a deletion request when a client opts out of data collection

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/glean#360]
Similar to [Bug 1585410](https://bugzilla.mozilla.org/show_bug.cgi?id=1585410) on Desktop, we need a mechanism for sending a data deletion request when a user opts out of data collection. 

Per discussion with @Dexterp37, there is an existing API for disabling data collection: `Glean.setUploadEnabled(false)`, we may want to send a deletion request at this point or design a new mechanism for sending a deletion request.

This functionality is needed by the end of 2019.

**Comment by Dexterp37** [comment]
I filed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1587095) for it, closing this as we're using Bugzilla for internal tracking ;) Thanks for filing!
