### ISSUE TITLE
nanos/millis confusion in event timestamp?

### ISSUE THREAD

**Issue by rfk** [mozilla/glean#452]
I noticed that the rust docs for `EventMetric.record` require a timestamp in nanoseconds:

https://github.com/mozilla/glean/blob/1f06101e4db4a2eff1b437f15f2f95456141e75a/glean-core/src/metrics/event.rs#L53

But the Kotlin bindings pass in the value of `SystemClock.elapsedRealtime()`, which is in milliseconds:

https://github.com/mozilla/glean/blob/1f06101e4db4a2eff1b437f15f2f95456141e75a/glean-core/android/src/main/java/mozilla/telemetry/glean/private/EventMetricType.kt#L116

Which is correct?

The docs also aren't clear what will happen if the passed-in timestamp is not monotonic; I happened to notice this because I passed a value in nanoseconds from rust code and then some android code passed a value in milliseconds and then there was a panic inside glean, but I don't know if that's the expected behaviour.

**Comment by Dexterp37** [comment]
Good catch @rfk - our [expected serialization format](https://mozilla.github.io/glean/book/dev/core/internal/payload.html#event) requires the timestamp to be in `milliseconds`. That's to match with the [desktop format](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/collection/events.html) that requires milliseconds.

At the very least, we need to fix comments in our Rust code. @rfk , where was the code panicking?

@mdboom since you implemented this, what do you think?

**Comment by rfk** [comment]
> @rfk , where was the code panicking?

If I can repro again I'll let you know more detail; the panic message was about an underflow during subtraction.

**Comment by Dexterp37** [comment]
> 
> 
> > @rfk , where was the code panicking?
> 
> If I can repro again I'll let you know more detail; the panic message was about an underflow during subtraction.

Oh, I see. This makes sense then, given that the magnitudes of milliseconds values vs nanoseconds should be very different.

**Comment by mdboom** [comment]
1. We definitely have a documentation bug we need to fix.  It should be milliseconds everywhere.

2. The code does assume that the timestamps are monotonic.  This has mostly been assured by using a single timer API that's guaranteed to be monotonic.  Using different sources of time has the possibility to break this assumption.  And even beyond that, as I squint at the code, there is a possibility of a race condition that might also produce non-monotonic values.

Fixing 1 is just documentation.  Fixing 2 should also be pretty easy -- we can just sort the timestamps on the way out.

**Comment by rfk** [comment]
(Also FWIW, I don't think it's unreasonable that directly calling into your FFI in unexpected ways can cause a panic - I just wasn't sure if it was expected or not)

**Comment by Dexterp37** [comment]
> 
> 
> (Also FWIW, I don't think it's unreasonable that directly calling into your FFI in unexpected ways can cause a panic - I just wasn't sure if it was expected or not)

Heheh, true :) The only way we support is calling our APIs through the automatically generated code :) Our FFI layer was not really meant to be used outside of our team. Still, that helped us catch 2 bugs, so thanks!

**Comment by travis79** [comment]
Has this been resolved?

**Comment by Dexterp37** [comment]
> 
> 
> Has this been resolved?

Yes. The [documentation](https://github.com/mozilla/glean/blob/f65a5a8bd6fc6207b951243dff24ac1e31b289c1/glean-core/src/metrics/event.rs#L53) is now correct. And #458 fixed the ordering. Closing this.
