### ISSUE TITLE
Documentation for Python SDK uses outdated API

### ISSUE THREAD

**Issue by hackebrot** [mozilla/glean#607]
According to the [documentation for the Python SDK][documentation] custom pings can be submitted as follows:

```python
from glean import load_pings
pings = load_pings("pings.yaml")
pings.search.submit()
```

I'm seeing an AttributeError for `glean-sdk==22.1.0`:

```text
AttributeError: 'PingType' object has no attribute 'submit'
```

I checked the wheel for the above version and it seems the API is now called `send`. 📝 

[documentation]: https://mozilla.github.io/glean/book/user/pings/custom.html#submitting-a-custom-ping

**Comment by mdboom** [comment]
The new API is `submit`.  So it's actually the release that is out-of-date.  Should be resolved by #615.
