### ISSUE TITLE
Error when using locally-published Glean in Fenix

### ISSUE THREAD

**Issue by emalysz** [mozilla/glean#697]
**Problem**
I followed the instructions from https://mozilla.github.io/glean/book/dev/howtos/locally-published-components-in-fenix.html, but I am still unable to run `./gradlew publishToMavenLocal` without errors in the glean repository root. Specifically: `can't open file 'null/build/tools/make_standalone_toolchain.py` after running a sudo command, or `java.nio.file.AccessDeniedException: /Users/emmamalysz/Desktop/glean/glean/glean-core/android/build/generated/source/buildConfig/release/mozilla/telemetry/glean/BuildConfig.java`when running the command normally.

**Additional Info**

- My .bash_profile includes `export ANDROID_NDK_ROOT="$HOME/android-ndk-r20b"` and `export ANDROID_NDK_HOME="$ANDROID_NDK_ROOT"`. I tried with the r20 NDK download as well as the one the doc currently points to (r21). The environment variables have the correct path when executing `printenv`

- I ran `rustup update` to ensure it is up to date and installed the targets.

- I edited the local.properties files to try both the emulator and 32 bit arm.

- I also tried installing NDK directly from Android studio

**Comment by Dexterp37** [comment]
Thank you for filing this, @emalysz ! I [moved this to Bugzilla(https://bugzilla.mozilla.org/show_bug.cgi?id=1614895), which is the main tool we use for tracking bugs. Closing it here.
