### ISSUE TITLE
Increases Firefox iOS binary size by 10%

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/glean#878]
Firefox iOS apk goes from 38MB to 42MB, a 10% increase in binary size, can we reduce the footprint of this lib? This will impact loading time at the DYLD stage, but also we have to control size creep over time so it is good to catch these growth spurts as they happen.

**Comment by Dexterp37** [comment]
I filed [this Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1637539) to track the issue on our end. Closing this ticket.

**Comment by garvankeeley** [comment]
Oops I'll use bugzilla in future, thanks for moving it over

**Comment by Dexterp37** [comment]
> 
> 
> Oops I'll use bugzilla in future, thanks for moving it over

No problem! There's anything wrong in using this issue tracker! We keep it open because it's simpler to use for some people and we just move stuff over when that happens ;-)
